//! SeaORM Entity. Generated by sea-orm-codegen 0.10.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "object")]
pub struct Model {
    #[serde(skip_serializing)]
    #[sea_orm(primary_key)]
    pub id: i32,
    pub object_name: String,
    pub object_type: String,
    pub object_size: i64,
    pub object_description: String,
    #[sea_orm(unique)]
    pub object_bucket_name: String,
    #[serde(skip_serializing)]
    pub block_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
